# PACS does not have a concept of a study with multiple subjects, so the Patient ID field must be used to infer which study
# an image corresponds to

# Define the overall pattern of the Patient ID that matches your study
patient_id_pattern: ^[0-9]{6}  [0-9]2[A-Z]{3}[0-9]{4}$
# If you want to extract the subject id instead of using full Patient ID when naming output directy, define subject id pattern here
patient_subject_id_pattern: ^[0-9]{6}